/*
Nombre: ACTUALIZANOTA
Autor:  Miguel Barillas
Fecha:  26/10/2013
Descripcion: Utilizado para actualizar la nota de un alumno
Nota: existe un procedimiento que se llama modificar nota que se utiliza 
en los tramites automatizados
Utilizado por: /Sistema/cambiarNota.aspx

Autor: Kevin Herrera
Fecha: 01/12/2014
Modificacion: Se cambia el tipo del parametro PFECHAIMP
*/
PROCEDURE ACTUALIZANOTA
(
  PCARNET   DBAFISICC.CAALUMNOSNOTASTB.CARNET%TYPE,
  PCARRERA  DBAFISICC.CAALUMNOSNOTASTB.CARRERA%TYPE,
  PNUEVANOTA DBAFISICC.CAALUMNOSNOTASTB.NOTA%TYPE,
  PCURSO    DBAFISICC.CAALUMNOSNOTASTB.CURSO%TYPE,
  PSTATUS   DBAFISICC.CAALUMNOSNOTASTB.CODSTATUS%TYPE,
  PRAZON    DBAFISICC.CAALUMNOSNOTASTB.RAZON%TYPE,
  PSECCION  DBAFISICC.CAALUMNOSNOTASTB.SECCION%TYPE,
  PTIPOASIG DBAFISICC.CAALUMNOSNOTASTB.TIPOASIG%TYPE,
  PFECHAIMP DBAFISICC.CAALUMNOSNOTASTB.FECHAIMP%TYPE,
  PSOLICITUD  DBAFISICC.SOMODINOTASTB.SOLICITUD%TYPE,
  PNOTAACTUAL DBAFISICC.SOMODINOTASTB.NOTA%TYPE,
  PUSUARIO  DBAFISICC.GNUSUARIOSTB.USUARIO%TYPE,
  PSQLCODE  OUT NUMBER
)AS

  VTRAMITE NUMBER(10,0);
  VMODIFICA  NUMBER;
  
BEGIN 

UPDATE DBAFISICC.CAALUMNOSNOTASTB A
  SET A.NOTA =PNUEVANOTA,  A.CODSTATUS = PSTATUS, A.RAZON = PRAZON, 
      A.FECHANOFIN = SYSDATE
        WHERE A.CARNET = PCARNET 
          AND A.CARRERA = PCARRERA 
          AND A.CURSO = PCURSO 
          AND A.SECCION = PSECCION 
          AND A.TIPOASIG = PTIPOASIG 
          AND TO_CHAR(A.FECHAIMP, 'YYYY-MM') = TO_CHAR(PFECHAIMP, 'YYYY-MM');

INSERT INTO DBAFISICC.AUDCAALUMNOSNOTASUSRTB
    SELECT C.CARNET, C.CURSO, C.CARRERA, C.SECCION, C.TIPOASIG, C.FECHAIMP, 
           C.CODSTATUS, C.FECHAASI, C.ZONA, C.EXAMFINAL, C.NOTA, C.FECHANOFIN, 
           C.HOJACAMBIO, C.COMENTARIO,C.CICLO, C.UMAS, C.RAZON, PUSUARIO, 
           SYSDATE, 'U' 
           
            FROM DBAFISICC.CAALUMNOSNOTASTB C 
            WHERE C.CARNET = PCARNET 
            AND C.CARRERA = PCARRERA 
            AND C.CURSO = PCURSO 
            AND C.SECCION = PSECCION 
            AND C.TIPOASIG = PTIPOASIG 
            AND TO_CHAR(C.FECHAIMP, 'YYYY-MM') = TO_CHAR(PFECHAIMP, 'YYYY-MM');
            

   BEGIN    
   
     SELECT 1 INTO VMODIFICA
     from DBAFISICC.SOMODINOTASTB
     where solicitud = PSOLICITUD
     and carrera = pcarrera
     and carnet = pcarnet
     and curso = pcurso
     and tipoasig = ptipoasig
     and seccion = pseccion
     AND TO_CHAR(FECHAIMP, 'YYYY-MM') = TO_CHAR(PFECHAIMP, 'YYYY-MM');

     
    EXCEPTION WHEN NO_DATA_FOUND THEN
          VMODIFICA := 0;   
    END;
    
   IF (VMODIFICA = 0)  THEN 
    
    INSERT INTO DBAFISICC.SOMODINOTASTB D
      (
       D.SOLICITUD
      ,D.CARRERA
      ,D.CARNET
      ,D.CURSO
      ,D.TIPOASIG
      ,D.SECCION
      ,D.FECHAIMP
      ,D.NOTA
      ,D.MODIFICACION
      ,D.USUARIO
      ,D.FECHAMODIFICACION
      )
    VALUES
      (
       PSOLICITUD
      ,PCARRERA
      ,PCARNET
      ,PCURSO
      ,PTIPOASIG
      ,PSECCION
      ,PFECHAIMP
      ,PNOTAACTUAL
      ,PNUEVANOTA
      ,PUSUARIO
      ,SYSDATE
      );
      
    else  
    
    UPDATE DBAFISICC.SOMODINOTASTB
    SET NOTA = PNOTAACTUAL,
        MODIFICACION = PNUEVANOTA,
        USUARIO = PUSUARIO,
        FECHAMODIFICACION = SYSDATE
     where solicitud = PSOLICITUD
     and carrera = pcarrera
     and carnet = pcarnet
     and curso = pcurso
     and tipoasig = ptipoasig
     and seccion = pseccion
     AND TO_CHAR(FECHAIMP, 'YYYY-MM') = TO_CHAR(PFECHAIMP, 'YYYY-MM');

     
    end if;
  
    SELECT D.TRAMITE INTO VTRAMITE
        FROM DBAFISICC.SOSOLTRAMITETB D
            WHERE D.SOLICITUD = PSOLICITUD;
            
    IF VTRAMITE = 81 THEN
      UPDATE DBAFISICC.SOSOLTRAMITETB E 
         SET E.OPERADO= 1 
           WHERE E.SOLICITUD =PSOLICITUD;
    END IF;
    
   PSQLCODE:=SQLCODE;   
 

 EXCEPTION 
     WHEN OTHERS THEN   
        PSQLCODE:=SQLCODE;
      
END ACTUALIZANOTA;