 /* 
   Autor: Kevin Herrera
   Fecha: 15/11/2014
   Descripcion: Devuelve las asignaciones ITC.
 */

 PROCEDURE ASIGNACIONESITC
 (
    PCARNET   DBAFISICC.CAASIGNACIONESTB.CARNET%TYPE DEFAULT NULL,
    PCARRERA  DBAFISICC.CAASIGNACIONESTB.CARRERA%TYPE DEFAULT NULL,
    RETVAL    OUT SYS_REFCURSOR
 )  
  AS BEGIN
   OPEN RETVAL FOR    
   
          SELECT A.CARRERA, A.CURSO, A.SECCION, B.NOMBRE, A.FECHAASIG 
                 AS FECHA_ASIGNO, C.HORARIO, A.PERIODO
            FROM DBAFISICC.CAASIGNACIONESTB A, DBAFISICC.CACURSOSTB B, 
                 DBAFISICC.CACURSHORATB C
            WHERE A.CARNET = PCARNET 
            AND A.CARRERA = PCARRERA 
            AND A.TIPOASIG = 'ITC'
            AND A.CURSO = B.CURSO 
            AND A.CARRERA = C.CARRERA 
            AND A.CURSO = C.CURSO 
            AND A.SECCION = C.SECCION 
            AND A.TIPOASIG = C.TIPOASIG;
            
 END ASIGNACIONESITC;