/*
Autor: Kevin Herrera.
Fecha: 25/06/2014
Descripcion: Procedimiento creado para obtener las secciones en el 
             modulo de asistencia.
*/

 PROCEDURE ASISTENCIASECCIONES
 (
    PENTIDAD   IN DBAFISICC.CACARRERASTB.ENTIDAD%TYPE DEFAULT NULL,
    PCARRERA   IN DBAFISICC.CACARRERASTB.CARRERA%TYPE DEFAULT NULL,
    PCICLO     IN DBAFISICC.caalumcarrstb.CICLO%TYPE DEFAULT NULL,
    retval     out sys_refcursor
  )
  IS  BEGIN
  OPEN RETVAL FOR  


    SELECT '0' SECCION, ' TODAS' DESCRIPCION
          from DUAL 
    
     UNION SELECT DISTINCT A.SECCION SECCION, D.DESCRIPCION DESCRIPCION
         
          FROM DBAFISICC.CAALUMCARRSTB A, DBAFISICC.CACARRERASTB B,
               DBAFISICC.CAUSUARIOSCARRERASTB C, DBAFISICC.CATIPOSECTB D
          where A.CARRERA  = B.CARRERA
          AND A.CARRERA  = C.CARRERA
          AND A.SECCION  = D.SECCION
          AND B.STATUC = 'A'
          AND (B.ENTIDAD = PENTIDAD OR PENTIDAD  IS NULL)
          AND (B.CARRERA = PCARRERA OR PCARRERA  IS NULL)
          AND (A.CICLO = PCICLO OR PCICLO is NULL);
          
 END ASISTENCIASECCIONES;          