/*
Autor:  Kevin Herrera.
Fecha:  21/07/2014
Descripcion: Procedimiento que devuelve los datos de asistencia de Docentes.
*/

PROCEDURE ASISTENCIA_INFODOCENTE
 (
    PHORARIO  DBAFISICC.RHASISTENCIATB.HORARIO%TYPE DEFAULT NULL,
    PFECHA    DBAFISICC.RHASISTENCIATB.FECHA%TYPE DEFAULT NULL,
    PCODPERS  DBAFISICC.RHASISTENCIATB.CodPers%TYPE DEFAULT NULL,
    RETVAL    OUT SYS_REFCURSOR
 )
  IS BEGIN
  OPEN RETVAL FOR 

     SELECT AUSENCIA, PUNTUALIDAD, TIEMPO, COMENTARIOS, AVISO, ATENDIO 
        
         FROM DBAFISICC.RHASISTENCIATB 
         WHERE HORARIO = PHORARIO
         AND TRUNC(FECHA) = TRUNC(PFECHA) 
         AND CODPUESTO IN('000010','000030','000081', '000085') 
         AND CODPERS = PCODPERS;

END ASISTENCIA_INFODOCENTE; 