/*
Autor:  Kevin Herrera.
Fecha:  21/07/2014
Descripcion: Procedimiento que devuelve los datos de asistencia de alumnos.
*/

PROCEDURE ASISTENCIA_INFOALUMNOS
 (
    PHORARIO  DBAFISICC.RHALUMASISTETB.HORARIO%TYPE DEFAULT NULL,
    PFECHA    DBAFISICC.RHALUMASISTETB.FECHA%TYPE DEFAULT NULL,
    PACCION   VARCHAR2,
    RETVAL    OUT SYS_REFCURSOR
 )
  IS BEGIN
  
  IF PACCION = '0' THEN
  OPEN RETVAL FOR 
  
      SELECT A.CARNET, A.CARRERA, B.APELLIDO1||' '||B.APELLIDO2 ||' '|| 
      B.NOMBRE1||' '|| B.NOMBRE2 ALUMNO, DECODE(A.AUSENCIA,0,'1','0') 
      ASISTENCIA 
                
                FROM DBAFISICC.RHALUMASISTETB A, DBAFISICC.CAALUMNOSTB B
                WHERE A.HORARIO=PHORARIO
                AND TRUNC(A.FECHA)=TRUNC(PFECHA)
                AND A.CARNET=B.CARNET 
                
      GROUP BY A.CARNET, A.CARRERA, B.APELLIDO1, B.APELLIDO2, B.NOMBRE1, 
               B.NOMBRE2, A.AUSENCIA 
      ORDER BY ALUMNO;
      
   ELSIF PACCION = '1' THEN
   OPEN RETVAL FOR    
   
      SELECT C.CARNET, C.CARRERA, D.APELLIDO1||' '||D.APELLIDO2 ||' '|| 
      D.NOMBRE1||' '|| D.NOMBRE2 ALUMNO, '1' ASISTENCIA 
                
                FROM DBAFISICC.CAMAINHORARIOSTB A, DBAFISICC.CACURSHORATB B, 
                DBAFISICC.CAASIGNACIONESTB C, DBAFISICC.CAALUMNOSTB D 
                WHERE A.HORARIO=PHORARIO 
                AND B.HORARIO=A.HORARIO 
                AND C.CARRERA=B.CARRERA
                AND C.CURSO=B.CURSO 
                AND C.TIPOASIG=B.TIPOASIG 
                AND C.SECCION=B.SECCION 
                AND C.CODSTATUS IN ('S1','S4') 
                AND D.CARNET=C.CARNET 
                
       GROUP BY C.CARNET, C.CARRERA, D.APELLIDO1, D.APELLIDO2, D.NOMBRE1, 
                D.NOMBRE2 
       ORDER BY ALUMNO;
       
    END IF;   
      
END ASISTENCIA_INFOALUMNOS;