/*
Autor:  Kevin Herrera.
Fecha:  15/03/2014
Descripcion: Procedimiento que devuelve los datos de asistencia de docentes.
*/

PROCEDURE ASISTENCIADOCENTES
(
    PHORARIO DBAFISICC.RHASISTENCIATB.HORARIO%TYPE DEFAULT NULL,
    PFECHAIMP varchar2 DEFAULT NULL,
    PACCION varchar2,
    RETVAL    OUT SYS_REFCURSOR
)
IS
BEGIN

 
 IF PACCION = 'A' THEN
  OPEN RETVAL FOR 
 
   SELECT A.CORRELATIVO,B.DIA, DECODE(B.DIA, 1, 'DOMINGO', 2, 'LUNES',3,
   'MARTES', 4, 'MIERCOLES', 5, 'JUEVES', 6, 'VIERNES',7,'SABADO') DIA,
   TO_CHAR(A.FECHA,'dd/MM/yyyy') FECHA, 
   B.TORRE||' - '||B.SALON SALON, TO_CHAR(B.HORAINI,'HH24:MI') HORAINI,
   TO_CHAR(B.HORAFIN,'HH24:MI') HORAFIN, 
   DECODE (A.AUSENCIA, 1, 'No asistió', 'Asistió') AUSENCIA, 
   DECODE (A.PUNTUALIDAD, 0, 'Puntual', 'Impuntual') PUNTUALIDAD, A.TIEMPO, 
   DECODE (A.COMENTARIOS, null, '-', A.COMENTARIOS) COMENTARIOS 

      FROM DBAFISICC.RHASISTENCIATB A, DBAFISICC.CAHORARIOSTB B 
      WHERE A.HORARIO=B.HORARIO 
      AND A.CORRELATIVO=B.CORRELATIVO 
      AND A.HORARIO=PHORARIO
      AND CODPUESTO='000010' 
      ORDER BY TO_DATE(A.FECHA,'dd/MM/yyyy')asc, HORAINI;

 ELSIF PACCION = 'H' THEN
  OPEN RETVAL FOR 
 
   SELECT A.CORRELATIVO,B.DIA, DECODE(B.DIA, 1, 'DOMINGO', 2, 'LUNES',3,
   'MARTES', 4, 'MIERCOLES', 5, 'JUEVES', 6, 'VIERNES',7,'SABADO') DIA, 
   TO_CHAR(A.FECHA,'dd/MM/yyyy') FECHA, 
   B.TORRE||' - '||B.SALON SALON, TO_CHAR(B.HORAINI,'HH24:MI') HORAINI,
   TO_CHAR(B.HORAFIN,'HH24:MI') HORAFIN, 
   DECODE (A.AUSENCIA, 1, 'No asistió', 'Asistió') AUSENCIA, 
   DECODE (A.PUNTUALIDAD, 0, 'Puntual', 'Impuntual') PUNTUALIDAD, 
   A.TIEMPO, DECODE (A.COMENTARIOS, null, '-', A.COMENTARIOS) COMENTARIOS 

      FROM DBAFISICC.RHHASISTENCIATB A, DBAFISICC.CAHHORARIOSTB B 
      WHERE A.HORARIO=B.HORARIO 
      AND A.CORRELATIVO=B.CORRELATIVO 
      AND A.FECHAIMP=B.FECHAIMP 
      AND A.HORARIO=PHORARIO
      AND A.FECHAIMP = TO_DATE(PFECHAIMP,'MM/yyyy') 
      AND CODPUESTO='000010' 
      order by TO_DATE(A.FECHA,'dd/MM/yyyy')asc, HORAINI;
  
  
 ELSIF PACCION = 'D' THEN
  OPEN RETVAL FOR 
   
   SELECT C.NOMBRE1||' '||C.NOMBRE2||' '||C.APELLIDO1||' '||C.APELLIDO2 
   CATEDRATICO 
   
     FROM DBAFISICC.RHHDOCENTESTB A, DBAFISICC.NOPUESTOSTB B, 
     DBAFISICC.NOPERSONALTB C 
     WHERE A.CODPUESTO=B.CODPUESTO 
     AND A.CODPERS=C.CODPERS 
     AND A.HORARIO=PHORARIO
     AND FECHAIMP=TO_DATE(PFECHAIMP,'MM/yyyy')
     AND A.STATUS='A' 
     AND B.CODPUESTO='000010' 
     
   UNION SELECT C.NOMBRE1||' '||C.NOMBRE2||' '||C.APELLIDO1||' '||C.APELLIDO2 
   VALOR 
   
     FROM RHDOCENTESTB A, NOPUESTOSTB B, NOPERSONALTB C 
     WHERE A.CODPUESTO=B.CODPUESTO 
     AND A.CODPERS=C.CODPERS 
     AND A.HORARIO=PHORARIO
     AND A.STATUS='A' 
     and b.CodPuesto='000010';

  END IF;

END ASISTENCIADOCENTES;