 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento que devuelve los datos de CATORRESTB.               
*/

 PROCEDURE INFOSALON
 (
   PHORARIO  IN DBAFISICC.CARESERVHORATMP.CODIGO%TYPE,
   PTORRE  IN DBAFISICC.CASALONESTB.TORRE%TYPE,
   PSALON  IN DBAFISICC.CASALONESTB.SALON%TYPE,
   RETVAL    OUT SYS_REFCURSOR
 ) 
 AS BEGIN    
  OPEN RETVAL FOR 
  
        SELECT A.HORARIO, A.DESCRIPCION, trunc(A.FECHAINI) 
        FECHAINI, trunc(A.FECHAFIN) FECHAFIN, A.CARHORA CARRERA, 
        B.INTERNET, B.PROYECTOR
              
              FROM DBAFISICC.CAMAINHORARIOSTB A, DBAFISICC.CASALONESTB B 
              WHERE A.HORARIO = PHORARIO
              AND B.TORRE = PTORRE
              AND B.SALON LIKE PSALON
                 
  END INFOSALON;

 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento que devuelve los datos de CATORRESTB.               
*/

 PROCEDURE INFOEVENTO
 (
   PHORARIO  IN DBAFISICC.CARESERVHORATMP.CODIGO%TYPE,
   RETVAL    OUT SYS_REFCURSOR
 ) 
 AS BEGIN    
  OPEN RETVAL FOR 
  
         SELECT A.CODIGO, trunc(A.FECHASOLIC) FECHASOLIC, 
         A.DESCRIPCION, A.USUARIO || ' - ' || A.SOLICITANTE SOLICITANTE, A.CUPO,
         A.EMAIL, B.DESCRIPCION TIPO, C.SOLICITUD
                
                 FROM DBAFISICC.CARESERVHORATMP A, DBAFISICC.CAUSOSALONTB B, 
                  DBAFISICC.SOSOLINFOTRAMITETB C
                 WHERE A.CODIGO = PHORARIO
                 AND C.CAMPOC = A.CODIGO
                 AND B.USO = A.USO;
                 
  END INFOEVENTO;
  
  /*
autor: Kevin Herrera
FECHA: 05/05/2014
Descripcion: Procedimiento para Insertar, actualizar y editar los datos de 
             la tabla GNTIPOINSTSTB.
*/

PROCEDURE TR_SOSOLINFOTRAMITETB 
 (  
   PSOLICITUD  IN DBAFISICC.SOSOLINFOTRAMITETB.SOLICITUD%TYPE,  
   PCODINFO    IN DBAFISICC.SOSOLINFOTRAMITETB.CODINFO%TYPE, 
   PTRAMITE    IN DBAFISICC.SOSOLINFOTRAMITETB.TRAMITE%TYPE, 
   PCAMPON     IN DBAFISICC.SOSOLINFOTRAMITETB.CAMPON%TYPE, 
   PCAMPOC     IN DBAFISICC.SOSOLINFOTRAMITETB.CAMPOC%TYPE, 
   PCAMPOF     IN DBAFISICC.SOSOLINFOTRAMITETB.CAMPOF%TYPE, 
   PSQLCODE    OUT NUMBER  
 )
  IS  
  BEGIN

       INSERT INTO DBAFISICC.SOSOLINFOTRAMITETB(SOLICITUD, CODINFO, TRAMITE, 
       CAMPON, CAMPOC, CAMPOF)
        
       VALUES(PSOLICITUD, PCODINFO, PTRAMITE, PCAMPON, PCAMPOC, PCAMPOF);

       PSQLCODE := SQLCODE;  
            
            EXCEPTION  
              WHEN OTHERS  THEN  
                  PSQLCODE := SQLCODE;
        
 END TR_SOSOLINFOTRAMITETB;
 
  /*
autor: Kevin Herrera
FECHA: 05/05/2014
Descripcion: Procedimiento para Insertar, actualizar y editar los datos de 
             la tabla GNTIPOINSTSTB.
*/

PROCEDURE TR_SOINFOTRAMITETB 
 (  
   PCODINFO      IN DBAFISICC.SOINFOTRAMITETB.CODINFO%TYPE,  
   PTRAMITE      IN DBAFISICC.SOINFOTRAMITETB.TRAMITE%TYPE, 
   PNOMCAMPO     IN DBAFISICC.SOINFOTRAMITETB.NOMCAMPO%TYPE, 
   PDESCRIPCION  IN DBAFISICC.SOINFOTRAMITETB.DESCRIPCION%TYPE, 
   PSQLCODE    OUT NUMBER  
 )
  IS  
  BEGIN 
       
       INSERT INTO SOINFOTRAMITETB(CODINFO, TRAMITE, NOMCAMPO, DESCRIPCION)
       VALUES(PCODINFO, PTRAMITE, PNOMCAMPO, PDESCRIPCION);
       
       PSQLCODE := SQLCODE;  
            
            EXCEPTION  
              WHEN OTHERS  THEN  
                  PSQLCODE := SQLCODE;
        
 END TR_SOINFOTRAMITETB;
 
  /*
autor: Kevin Herrera
FECHA: 05/05/2014
Descripcion: Procedimiento para Insertar, actualizar y editar los datos de 
             la tabla GNTIPOINSTSTB.
*/

PROCEDURE SOLICITARSALONEVENTO 
 (  
   PDESCRIPCION  IN DBAFISICC.CAMAINHORARIOSTMP.DESCRIPCION%TYPE,  
   PFECHAINICIO  IN DBAFISICC.CAMAINHORARIOSTMP.FECHAINI%TYPE, 
   PFECHAFIN     IN DBAFISICC.CAMAINHORARIOSTMP.FECHAFIN%TYPE,
   PSTATUS       IN DBAFISICC.CAMAINHORARIOSTMP.STATUS%TYPE,
   PHORARIO      IN DBAFISICC.CAHORARIOSTMP.HORARIO%TYPE,
   PCORRELATIVO  IN DBAFISICC.CAHORARIOSTMP.CORRELATIVO%TYPE,
   PDIA          IN DBAFISICC.CAHORARIOSTMP.DIA%TYPE,
   PHORAINI      IN DBAFISICC.CAHORARIOSTMP.HORAINI%TYPE,
   PHORAFIN      IN DBAFISICC.CAHORARIOSTMP.HORAFIN%TYPE,
   PTORRE        IN DBAFISICC.CAHORARIOSTMP.TORRE%TYPE,
   PSALON        IN DBAFISICC.CAHORARIOSTMP.SALON%TYPE,
   PCODPERS      IN DBAFISICC.CAHORARIOSTMP.CODPERS%TYPE,
   PCUPO         IN DBAFISICC.CARESERVHORATMP.CUPO%TYPE,
   PSOLICITANTE  IN DBAFISICC.CARESERVHORATMP.SOLICITANTE%TYPE,
   PUSUARIO      IN DBAFISICC.CARESERVHORATMP.USUARIO%TYPE,
   PEMAIL        IN DBAFISICC.CARESERVHORATMP.EMAIL%TYPE,
   PUSO          IN DBAFISICC.CARESERVHORATMP.USO%TYPE,
   PSQLCODE      OUT NUMBER  
 )
  IS  
  BEGIN  
               
      INSERT INTO DBAFISICC.CAMAINHORARIOSTMP(HORARIO, DESCRIPCION, FECHAINI, 
      FECHAFIN, STATUS) 
          
      values(PHORARIO, PDESCRIPCION, PFECHAINICIO, PFECHAFIN, PSTATUS);
                      
                      
      INSERT INTO DBAFISICC.CAHORARIOSTMP(HORARIO, CORRELATIVO, DIA, HORAINI,
      HORAFIN, SALON, TORRE, CODPERS) 
                    
      VALUES(PHORARIO, PCORRELATIVO, PDIA, PHORAINI, PHORAFIN, PSALON, PTORRE, 
      PCODPERS);
                      
      INSERT INTO DBAFISICC.CARESERVHORATMP(CODIGO, FECHASOLIC, DESCRIPCION,
      SOLICITANTE, CUPO, STATUS, INTERNET, USUARIO, EMAIL, USO) 
        
      VALUES(PHORARIO, PFECHAINICIO, PDESCRIPCION, PSOLICITANTE, PCUPO, 
      PSTATUS, 'S', PUSUARIO, PEMAIL, PUSO);
        
      PSQLCODE := SQLCODE;  
      
      EXCEPTION  
        WHEN OTHERS  THEN  
            PSQLCODE := SQLCODE;
        
 END SOLICITARSALONEVENTO;

 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento creado para generar correlativo para nuevas
             torres que se ingresen.
*/

PROCEDURE GENCODIGOEVENTO
( 
  HORARIO out varchar2
)
  IS
  BEGIN 
   
      SELECT 'EV' || LPAD(TO_CHAR(COUNT(CODIGO) + 1), 6-LENGTH('EV'),'0')
      INTO HORARIO
            FROM DBAFISICC.CARESERVHORATMP;

 END GENCODIGOEVENTO;

 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento que devuelve los datos de CATORRESTB.               
*/

 PROCEDURE ALUMNOSXSALON
 (
   PHORARIO  IN DBAFISICC.CAMAINHORARIOSTB.HORARIO%TYPE,
   RETVAL  OUT SYS_REFCURSOR
 ) 
  AS BEGIN    
  OPEN RETVAL FOR 
  
       SELECT E.HORARIO,E.DESCRIPCION, COUNT(D.CARNET) as total
              
              FROM DBAFISICC.CACURSHORATB B, DBAFISICC.CACURSOSIMPTB C,
              DBAFISICC.CAASIGNACIONESTB D, DBAFISICC.CAMAINHORARIOSTB E
              WHERE e.HORARIO = PHORARIO
              AND B.HORARIO = E.HORARIO
              AND C.CARRERA = B.CARRERA
              AND C.CURSO = B.CURSO
              AND C.TIPOASIG = B.TIPOASIG
              AND C.SECCION = B.SECCION 
              AND D.CARRERA = C.CARRERA
              AND D.CURSO = C.CURSO
              AND D.TIPOASIG = C.TIPOASIG 
              AND D.SECCION = C.SECCION
              AND D.CODSTATUS IN ('S1','S4')
          
          GROUP BY E.HORARIO,E.DESCRIPCION;
          
 END ALUMNOSXSALON;

 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento que devuelve los datos de CATORRESTB.               
*/

 PROCEDURE SALONESOLICITADOS
 (
   PTORRE  IN DBAFISICC.CAHORARIOSTMP.TORRE%TYPE,
   PNIVEL  IN DBAFISICC.CAHORARIOSTMP.SALON%TYPE,
   PFECHA  IN DBAFISICC.CAMAINHORARIOSTMP.FECHAINI%TYPE,
   PDIA    IN DBAFISICC.CAHORARIOSTMP.DIA%TYPE,
   RETVAL  OUT SYS_REFCURSOR
 ) 
 AS BEGIN    
  OPEN RETVAL FOR 

     SELECT DISTINCT A.HORARIO, (A.SALON), TO_CHAR(A.HORAINI,'HH24:MI')AS HORAINI,
     TO_CHAR(A.HORAFIN,'HH24:MI')AS HORAFIN
        
            FROM DBAFISICC.CAHORARIOSTMP A, DBAFISICC.CAMAINHORARIOSTMP B
            WHERE A.TORRE= PTORRE 
            AND A.SALON LIKE PNIVEL
            AND TRUNC(PFECHA) BETWEEN TRUNC(B.FECHAINI) AND TRUNC(B.FECHAFIN) 
            AND A.DIA = PDIA
            AND B.HORARIO=A.HORARIO;
 
 END SALONESOLICITADOS;

 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento que devuelve los datos de CATORRESTB.               
*/

 PROCEDURE SALONESENUSO  
 (
   PTORRE  IN DBAFISICC.CAHORARIOSTB.TORRE%TYPE,
   PNIVEL  IN DBAFISICC.CAHORARIOSTB.SALON%TYPE,
   PFECHA  IN DBAFISICC.CAMAINHORARIOSTB.FECHAINI%TYPE,
   PDIA    IN DBAFISICC.CAHORARIOSTB.DIA%TYPE,
   RETVAL  OUT SYS_REFCURSOR
 ) 
 AS BEGIN    
  open RETVAL for 

    SELECT DISTINCT(A.SALON), A.HORARIO AS HORARIO,
    TO_CHAR(A.HORAINI,'HH24:MI')AS HORAINI,
    TO_CHAR(A.HORAFIN,'HH24:MI')AS HORAFIN
       
       FROM DBAFISICC.CAHORARIOSTB A,DBAFISICC.CAMAINHORARIOSTB B 
       WHERE A.TORRE=PTORRE 
       AND A.SALON LIKE PNIVEL
       AND TRUNC(PFECHA) BETWEEN TRUNC(B.FECHAINI) AND TRUNC(B.FECHAFIN) 
       AND A.DIA = PDIA
       AND B.HORARIO = A.HORARIO;
 
 END SALONESENUSO;

 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento que devuelve los datos de CATORRESTB.               
*/

 PROCEDURE SALONESXTORRENIVEL  
 (
   PTORRE  IN DBAFISICC.CASALONESTB.TORRE%TYPE,
   PNIVEL  IN DBAFISICC.CASALONESTB.SALON%TYPE,
   RETVAL  OUT SYS_REFCURSOR
 ) 
 AS BEGIN    
  open RETVAL for 
  
      SELECT SALON,CUPO
          FROM DBAFISICC.CASALONESTB
          WHERE TORRE= PTORRE
          AND SALON LIKE PNIVEL
      order by salon;
    
 END SALONESXTORRENIVEL; 

 /*
autor: Kevin Herrera
FECHA: 02/04/2014
Descripcion: Procedimiento que devuelve los datos de CATORRESTB.               
*/

 PROCEDURE SEL_CAUSOSALONTB  
 (
   RETVAL  OUT SYS_REFCURSOR
 ) 
 AS BEGIN    
  open RETVAL for 
  
   SELECT USO, DESCRIPCION, AUTORIZA 
      FROM DBAFISICC.CAUSOSALONTB;
    
 END SEL_CAUSOSALONTB; 