SELECT * FROM SOSOLINFOTRAMITETB
desc SOSOLINFOTRAMITETB
select * from SoInfoTramiteTB

select * from sotramitestb
select * from sosoltramitetb
SELECT * FROM SOSOLICITUDESTB

INSERT INTO SOINFOTRAMITETB(CODINFO, TRAMITE, NOMCAMPO, DESCRIPCION)
VALUES(1, 405, 'CAMPOC', 'HORARIO POR EVENTO')

INSERT INTO SOINFOTRAMITETB(CODINFO, TRAMITE, NOMCAMPO, DESCRIPCION)
values(2, 405, 'CAMPOC', 'HORARIO POR EVENTO')


INSERT INTO SOTRAMITESTB(TRAMITE, DESCRIPCION, TIPO, REGULAR)
VALUES(405, 'Solicitud de Eventos', 'AD', 'NR')

DBAFISICC.PKG_SOLICITUDES_SP.TRASLADAREVENTO
DBAFISICC.PKG_SOLICITUDES_SP.ELIMINAREVENTO