create or replace procedure CREARUSUARIOADMINISTRATIVO  
  (    
    PEMPLEADO PL47.ARPLME.NO_EMPLE%type default null,
    RETVAL  OUT SYS_REFCURSOR  
  )    
  as      
  begin    
  open RETVAL for 

select NOMBRE_PILA,APE_PAT,APE_MAT,SEXO,E_CIVIL,CIUDAD_CEDULA,CEDULA,ASEGU
,NONIT,TO_CHAR(F_NACIMI,'dd/MM/yyyy')F_NACIMI,PAIS,ESTADO,PAIS_NAC
,TO_CHAR(F_INGRESO,'dd/MM/yyyy') F_INGRESO,DDEPTO,MUNICIPIO,PASAPORTE,
CORRELATIVO,EMAIL,NO_CIA,DIRECCION,TELEFONO,ID_PAIS,ID_DEPTO,ID_MUNICIPIO 

from PL47.ARPLME 
where NO_EMPLE = PEMPLEADO;

END CREARUSUARIOADMINISTRATIVO;