 /* 
   Autor: Kevin Herrera
   Fecha: 12/11/2014
   Descripcion: Devuelve los cursos que impartio un docente y pago prestaciones.
 */

 PROCEDURE CURSOSPRESTACIONES
 (
    PCODPERS    DBAFISICC.RHHDOCENTESTB.CODPERS%TYPE DEFAULT NULL,
    PCODPUESTO  DBAFISICC.RHHDOCENTESTB.CODPUESTO%TYPE DEFAULT NULL,
    RETVAL    OUT SYS_REFCURSOR
 )  
  AS BEGIN
   OPEN RETVAL FOR
    
   SELECT B.CURSO, B.NOMBRE
     
     FROM (SELECT DISTINCT B.CURSO 
              FROM DBAFISICC.RHHDOCENTESTB A, DBAFISICC.CAHCURSHORATB B, 
                   DBAFISICC.CAHMAINHORARIOSTB C, DBAFISICC.NOPUESTOSTB D
              WHERE A.HORARIO = B.HORARIO
              AND A.FECHAIMP = B.FECHAIMP
              AND A.HORARIO = C.HORARIO
              AND A.FECHAIMP = C.FECHAIMP
              AND A.CODPUESTO = D.CODPUESTO
              AND A.STATUS IN ('A','P')
              AND B.TIPOASIG IN('AS','DT','SEM')
              AND A.CODPERS = PCODPERS
              AND (A.CODPUESTO = PCODPUESTO OR PCODPUESTO IS NULL)
              AND EXISTS (SELECT 1 
                            FROM DBAFISICC.NOHDOCXHORARIOTB 
                            WHERE HORARIO = A.HORARIO)) A, 
           DBAFISICC.CACURSOSTB B
      WHERE A.CURSO = B.CURSO
      
     ORDER BY B.NOMBRE;
  
 END CURSOSPRESTACIONES;