 /*
autor: Kevin Herrera
FECHA: 11/04/2014
Descripcion: Procedimiento que devuelve los datos de departamentos.
*/

PROCEDURE DEPARTAMENTOS  
 (
   PPAIS DBAFISICC.GNDEPTOSTB.PAIS%TYPE DEFAULT NULL,
   RETVAL  OUT SYS_REFCURSOR
 ) 
 AS BEGIN
  OPEN RETVAL FOR   
  
    SELECT A.PAIS, A.DEPTO, A.NOMBRE, A.DEPTO_INE, A.ASEGURADORA, 
           B.NOMBRE AS PAISNOMBRE
           
       FROM DBAFISICC.GNDEPTOSTB A, DBAFISICC.GNPAISESTB B
       WHERE B.PAIS = A.PAIS
       AND (A.PAIS = PPAIS OR PPAIS IS NULL)
    ORDER BY B.NOMBRE, A.NOMBRE;

END DEPARTAMENTOS;    