/*
Autor: Kevin Herrera.
Fecha: 25/06/2014
Descripcion: Procedimiento creado para obtener los docentes en el 
             modulo de asistencia.
*/

 PROCEDURE DOCENTESASISTENCIA
 (
    PDIA       IN DBAFISICC.CAHORARIOSTB.DIA%TYPE DEFAULT NULL,
    PFECHA     IN DBAFISICC.CAMAINHORARIOSTB.FECHAINI%TYPE DEFAULT NULL,
    PHORAINI   IN DBAFISICC.CAHORARIOSTB.HORAINI%TYPE DEFAULT NULL,
    PHORAFIN   IN DBAFISICC.CAHORARIOSTB.HORAFIN%TYPE DEFAULT NULL,
    PENTIDAD   IN DBAFISICC.CACARRERASTB.ENTIDAD%TYPE DEFAULT NULL,
    PUSUARIO   IN DBAFISICC.CAUSUARIOSCARRERASTB.USUARIO%TYPE DEFAULT NULL,
    PHORARIO   IN DBAFISICC.CAMAINHORARIOSTB.HORARIO%TYPE DEFAULT NULL,
    PCARRERA   IN DBAFISICC.CACURSHORATB.CARRERA%TYPE DEFAULT NULL,
    retval     out sys_refcursor
  )
  IS  BEGIN
  OPEN RETVAL FOR           
            
     SELECT '0' CODPERS, ' TODOS' NOMBRE 
         from dual

     UNION  SELECT E.CODPERS, E.CODPERS|| ' - ' ||E.APELLIDO1||' '||NVL(E.APELLIDO2,'')||', '
     ||e.nombre1||' '||NVL(e.nombre2,'') Nombre
            
         FROM DBAFISICC.CAMAINHORARIOSTB A, DBAFISICC.CACURSHORATB B, 
         DBAFISICC.CAHORARIOSTB C, DBAFISICC.RHDOCENTESTB D, 
         DBAFISICC.NOPERSONALTB E, DBAFISICC.CACARRERASTB F,
         DBAFISICC.CAUSUARIOSCARRERASTB G   
         WHERE A.HORARIO=B.HORARIO 
         AND A.HORARIO=C.HORARIO 
         AND D.HORARIO=A.HORARIO  
         AND B.CARRERA=G.CARRERA 
         AND CODPUESTO IN ('000010', '000081') 
         and d.CodPers=e.CodPers
         AND B.CARRERA=F.CARRERA
         AND (G.USUARIO=PUSUARIO OR PUSUARIO IS NULL)
         AND (F.ENTIDAD = PENTIDAD OR PENTIDAD IS NULL)
         AND (B.CARRERA = PCARRERA OR PCARRERA IS NULL)
         AND (A.HORARIO = PHORARIO OR PHORARIO IS NULL)
         AND (C.DIA=PDIA OR PDIA IS NULL) 
         AND  trunc(PFECHA) BETWEEN trunc(A.FECHAINI) AND trunc(A.FECHAFIN)
         AND TO_CHAR(C.HORAINI, 'HH24:MI') BETWEEN TO_CHAR(PHORAINI, 'HH24:MI') 
                                               AND TO_CHAR(PHORAFIN, 'HH24:MI')
         AND G.ASISTENCIA =1  
     
     ORDER BY NOMBRE;
     
 END DOCENTESASISTENCIA;     