/*
AUTOR:  AMILCAR MARTINEZ 
FECHA:  24/07/2014
PAQUETE: PKG_
DESCRIPCION: REALIZA LOS FRACCIONAMIENTOS DE PAGOS POR ALUMNO. 
*/


 PROCEDURE FRACCIONAMIENTO 
 (
   PUSUARIO                DBAFISICC.GNUSUARIOSTB.USUARIO%TYPE,
   PCARNET                 DBAFISICC.CAALUMCARRSTB.CARNET%TYPE,
   PCARRERA                DBAFISICC.CAALUMCARRSTB.CARRERA%TYPE,
   PPENSUM                 DBAFISICC.CAALUMCARRSTB.PENSUM%TYPE,
   PCODMOVTO               DBAFISICC.CCTIPOMOVTOTB.CODMOVTO%TYPE,
   PCURSO                  DBAFISICC.CACURSOSTB.CURSO%TYPE,
   PMONTO                  DBAFISICC.CCEDOCTATB.MONTO%TYPE,
   PSOLICITUD              DBAFISICC.CCEDOCTATB.OPERACION%TYPE,
   PFRACCION               DBAFISICC.CCEDOCTATB.FRACCION%TYPE,
   PINI_FRAC               DBAFISICC.CCEDOCTATB.INI_FRAC%TYPE,
   PCENTRO                 DBAFISICC.CCEDOCTATB.CENTRO%TYPE,
   POBSERVACIONES          DBAFISICC.CCEDOCTATB.OBSERVACIONES%TYPE,
   PTIPO                   VARCHAR2,
   PSQLCODE                OUT NUMBER
  )
  IS
    ALERT_ID               NUMBER;
    ABONOS_MOVTO           CCEDOCTATB.MONTO%TYPE;
    VNUMCTA                CCEDOCTATB.NUMCTA%TYPE;
    VCORRELATIVO           CCEDOCTATB.CORRELATIVO%TYPE;

  BEGIN
   
   SELECT MAX(NVL(A.CORRELATIVO,0)) INTO VCORRELATIVO
      FROM DBAFISICC.CCEDOCTATB A
      WHERE CARNET = PCARNET
      AND   CARRERA = PCARRERA;
   
   VCORRELATIVO := VCORRELATIVO + 1;

   SELECT A.PERIODO INTO VNUMCTA
     FROM DBAFISICC.CACARRERASTB A
     WHERE CARRERA = PCARRERA;
     
   INSERT INTO DBAFISICC.CCEDOCTATB(PENSUM, CARRERA, CARNET, CORRELATIVO, 
   NUMCTA, CODMOVTO, FECHA, MONTO, CARGO_ABONO, CURSO, OBSERVACIONES, OPERACION,
   FRACCION,INI_FRAC,CENTRO)
   
   VALUES(PPENSUM, PCARRERA, PCARNET, VCORRELATIVO, VNUMCTA,PCODMOVTO, 
   TRUNC(SYSDATE),PMONTO,PTIPO,PCURSO,PUSUARIO||' - '||POBSERVACIONES,
   PSOLICITUD, PFRACCION,PINI_FRAC,PCENTRO);  
     
   PSQLCODE := SQLCODE;  
      
   EXCEPTION  
    WHEN OTHERS  THEN  
        PSQLCODE := SQLCODE;   

 END FRACCIONAMIENTO;