/*
Autor:  Kevin Herrera.
Fecha:  18/03/2014
Descripcion: Procedimiento que devuelve los horarios por empleado y tambien 
             los horarios si este es alumno.
Modificacion: Autor: Kevin Herrera
Fecha: 21/04/2014
Descripcion: se agrego el campo correlativo al select de HORARIO.
*/
PROCEDURE HORARIOXEMPLEADO
 (
    PNOMBRE DBAFISICC.NOPERSONALTB.NOMBRE1%TYPE DEFAULT NULL,
    PCODPERS DBAFISICC.NOPERSONALTB.CODPERS%TYPE DEFAULT NULL,
    PCARNET DBAFISICC.CAALUMNOSTB.CARNET%TYPE DEFAULT NULL,
    PACCION varchar2,
    RETVAL    OUT SYS_REFCURSOR
 )
  IS
  BEGIN

  IF PACCION = 'NOMBRE' THEN
   OPEN RETVAL FOR 
   
     SELECT DISTINCT codpers
      FROM NOPERSONALTB
      WHERE NOMBRE1 || ' ' || NOMBRE2 || ' ' || APELLIDO1 || ' ' || 
            APELLIDO2 || ' ' || DECASADA LIKE '%'||PNOMBRE||'%';
      
  ELSIF PACCION = 'CODPERS' THEN
    OPEN RETVAL FOR  
        
      select f.carnet
        FROM NOPERSONALTB E, CAALUMNOSTB F 
        WHERE E.CODPERS= PCODPERS
        and e.correlativo=f.correlativo ;

  ELSIF PACCION = 'HORARIO' THEN
    OPEN RETVAL FOR  
        
     SELECT A.DESCRIPCION AS NOMBRE, E.DESPUESTO, 
     TO_CHAR(A.FECHAINI,'DD/MM/YYYY') AS FECHAINI, 
     TO_CHAR(A.FECHAFIN,'DD/MM/YYYY') AS FECHAFIN,
     B.DIA AS DIA, B.TORRE AS TORRE, B.SALON AS SALON, 
     B.HORAINI AS HORAINI,TO_CHAR (B.HORAINI, 'hh') AS HORAINIH, 
     TO_CHAR (B.HORAINI, 'mi') AS HORAINIM, 
     to_number(to_char(b.horaini,'hh24'))*100 +
     TO_NUMBER(TO_CHAR(B.HORAINI,'mi')) AS HIM, B.HORAFIN AS HORAFIN, 
     TO_CHAR (B.HORAFIN, 'hh') AS HORAFINH, TO_CHAR (B.HORAFIN, 'mi') 
     AS HORAFINM, TO_NUMBER(TO_CHAR(B.HORAFIN,'hh24'))*100 + 
     to_number(to_char(b.horafin,'mi')) AS Hfm, a.horario, b.correlativo
       
       FROM DBAFISICC.CAMAINHORARIOSTB A, DBAFISICC.CAHORARIOSTB B, 
       DBAFISICC.NOPERSONALTB C, DBAFISICC.RHDOCENTESTB D, 
       DBAFISICC.NOPUESTOSTB E
       WHERE B.HORARIO = A.HORARIO
       AND A.HORARIO = D.HORARIO
       AND D.CODPERS = C.CODPERS
       AND D.CODPUESTO = E.CODPUESTO
       and d.codpuesto != '000013'
       AND D.CODPERS = PCODPERS
       AND d.STATUS = 'A'
 
     UNION SELECT A.DESCRIPCION NOMBRE,'ESTUDIANTE' PUESTO, 
     TO_CHAR(A.FECHAINI,'DD/MM/YYYY') FECHAINI,
     TO_CHAR(A.FECHAFIN,'DD/MM/YYYY') FECHAFIN,B.DIA DIA, B.TORRE TORRE, 
     B.SALON SALON,B.HORAINI HORAINI, TO_CHAR (B.HORAINI, 'hh') AS HORAINIH, 
     TO_CHAR (B.HORAINI, 'mi') AS HORAINIM, 
     TO_NUMBER(TO_CHAR(B.HORAINI,'hh24'))*100 + 
     TO_NUMBER(TO_CHAR(B.HORAINI,'mi')) AS HIM, B.HORAFIN HORAFIN,  
     TO_CHAR (B.HORAFIN, 'hh') AS HORAFINH, TO_CHAR (B.HORAFIN, 'mi') 
     AS HORAFINM, TO_NUMBER(TO_CHAR(B.HORAFIN,'hh24'))*100 + 
     TO_NUMBER(TO_CHAR(B.HORAFIN,'mi')) AS HFM, A.HORARIO, b.correlativo 
 
      FROM DBAFISICC.CAMAINHORARIOSTB A, DBAFISICC.CAHORARIOSTB B, 
      DBAFISICC.CACURSHORATB C, DBAFISICC.CAASIGNACIONESTB D
      WHERE B.HORARIO = A.HORARIO
      and c.horario = a.horario
      AND C.CURSO   = D.CURSO
      and c.carrera = d.carrera
      AND C.SECCION = D.SECCION
      AND C.TIPOASIG = D.TIPOASIG
      AND D.CARNET = (SELECT F.CARNET
                       FROM NOPERSONALTB E, CAALUMNOSTB F
                       WHERE E.CODPERS=PCODPERS
                       AND E.CORRELATIVO=F.CORRELATIVO
                       AND (F.CARNET = PCARNET OR PCARNET IS NULL))
      AND D.CODSTATUS  IN ('S1','S4')
      ORDER BY DIA, HIM;
  
  END IF;
END HORARIOXEMPLEADO;