 /*
autor: Kevin Herrera
FECHA: 24/03/2014
Descripcion: Procedimiento que devuelve la informacion de la carrera que se
             envia por el parametro PCARRERA.
*/

PROCEDURE INFORMACIONXCARRERA
(
  PCARRERA DBAFISICC.CACARRERASTB.CARRERA%TYPE DEFAULT NULL,
  RETVAL    OUT SYS_REFCURSOR
)
 IS
  BEGIN
   OPEN RETVAL FOR

     SELECT CARRERA, ENTIDAD, FACULTAD, NOMBRE, ENCARGADO, TIPOCICLO, TIPOCOBRO, 
      PRECIO, COBROINS, COMENTARIOS, CICLOACT, NOMBRE_CORTO, INTERNET, 
      PENSUM_VIGENTE, STATUC, NIVEL, MAINCAR, CC, ORDEN, GRADO, RESOLUCION, 
      PERIODO, NEXTTERM, AGENCIA, UBICACION, CENTRO, NVL(PRIVADO,0) AS PRIVADO, 
      PAGO6TO, SECRETARIA, NVL(LIQUIDACION,0) AS LIQUIDACION, SECRETARIA2, 
      CONTROLACADEMICO, TIPO, LOCALIDAD, PBMT, PBCT, MAXALUM, SECRETARIA3, 
      NVL(PAGODOCENTES,0) AS PAGODOCENTES, FIRMA, NVL(MUXCT,0) AS MUXCT, 
      NOMBRE_INGLES, SIGNATURE, EXAUBI, PERIODOCLASE, PERIODOSXSEMANA, 
      SEMANASCLASE, TIPOBECA 
  
        FROM DBAFISICC.CACARRERASTB 
        WHERE carrera = PCARRERA;

END INFORMACIONXCARRERA;