/*
autor: Kevin Herrera
FECHA: 18/02/2014
Descripcion: Procedimiento creado que modifica los usuarios en la tabla 
GNUSUARIOSTB e inserta en la tabla de Auditoria correspondiente
*/
 procedure MODIFICARUSUARIO  
  (    
    PUSUARIO DBAFISICC.GNUSUARIOSTB.USUARIO%type default null,
    PNOMBRE DBAFISICC.GNUSUARIOSTB.NOMBRE%type default null,
    PEMAIL DBAFISICC.GNUSUARIOSTB.EMAIL%type default null,
    PCODPERS DBAFISICC.GNUSUARIOSTB.CODPERS%type default null,
    PUSUNAF  DBAFISICC.GNUSUARIOSTB.USUNAF%type default null,
    PACCESO_CC DBAFISICC.GNUSUARIOSTB.ACCESO_CC%type default null,
    PACCESO_CCAUD DBAFISICC.GNUSUARIOSTB.ACCESO_CCAUD%type default null,
    PTRASLADO_REC DBAFISICC.GNUSUARIOSTB.TRASLADO_REC%type default null,
    PUFM DBAFISICC.GNUSUARIOSTB.ACCESO_UPDUFM%type default null,
    PNOMINA DBAFISICC.GNUSUARIOSTB.ACCESO_NOMINA_DOCENTE%type default null,
    PDEPTO DBAFISICC.GNUSUARIOSTB.REFERENCIA%type default null,
    PORACLE DBAFISICC.GNUSUARIOSTB.ORACLE%type default null,
    PACTIVO DBAFISICC.GNUSUARIOSTB.ACTIVO%type default null,
    PUSERAUDITORIA AUDITORIA_DB.AUDUSUARIOSUSRTB.USUARIO_AUD%type default null,
    PSTATUS AUDITORIA_DB.AUDUSUARIOSUSRTB.ACCOUNT_STATUS%type default null
     ) 
  is
  begin 

    update DBAFISICC.GNUSUARIOSTB set NOMBRE=PNOMBRE, CODPERS=PCODPERS,
    EMAIL=PEMAIL, USUNAF=PUSUNAF, ACCESO_CC= PACCESO_CC, 
    ACCESO_CCAUD= PACCESO_CCAUD, TRASLADO_REC= PTRASLADO_REC, 
    ACCESO_UPDUFM= PUFM, ACCESO_NOMINA_DOCENTE = PNOMINA, 
    REFERENCIA=PDEPTO ,ORACLE = PORACLE , ACTIVO= PACTIVO
    where USUARIO=PUSUARIO;

   insert into AUDITORIA_DB.AUDUSUARIOSUSRTB(USUARIO ,NOMBRE ,EMAIL ,
   CODPERS,USUNAF,ACCESO_CC, ACCESO_CCAUD, TRASLADO_REC, ACCESO_UPDUFM, 
   ACCESO_NOMINA_DOCENTE, ACTIVO, REFERENCIA, ACCOUNT_STATUS, MOVIMIENTO, 
   USUARIO_AUD, FECHA)

   values(PUSUARIO,PNOMBRE,PEMAIL,PCODPERS,'N','','','','','',PACTIVO,PDEPTO,
   PSTATUS,'U',PUSERAUDITORIA,sysdate);


 END MODIFICARUSUARIO;