/*AUTOR: KEVIN HERRERA
  FECHA: 16/01/2014
  DESCRIPCION: PROCEDIMIENTO QUE DEVUELVE LOS PUESTOS PARA ASISTENCIA
  DE DOCENTES, UNICAMENTE DEVUELVE LOS PUESTO AUTORIZADOS*/
  
  
CREATE OR REPLACE PROCEDURE PUESTOS_ASISTENCIA
  (
    RETVAL    OUT sys_refcursor
  ) AS 
  begin
    OPEN RETVAL FOR

select CODPUESTO, DESPUESTO
    from DBAFISICC.NOPUESTOSTB 
       where CODPUESTO in  ('000010','000074');
    
END PUESTOS_ASISTENCIA;
    
    