/*
Nombre:       REP_INSCRITOS.
Autor:        Jorge Velásquez
Fecha:        15/10/2012
Package:      PKG_REPORTES
Descripción:  Devuelve la cantidad de alumnos graduados por los diferentes
			parametros recibidos, utilizado para los cuadros comparativos.
			
			Si en PANIO se recibe 0, es devuelta la cantidad de alumnos
			inscritos actualmente, al recibir un año se devuelve la cantidad
			de alumnos inscritos desde ese año hasta el año actual.
			
			El procedimiento es utilizado por InscritosPorGenero.rdl.
Modificación: AALVARADO - 09/01/2014 - SE AGREGO EL STATUS DEL ALUMNO PARA EL 
REPORTE. 
AALVARADO - 14/01/2014 - Se cambio que en la opcion de APOSADAS acepte 
todas las facultades. 
AALVARADO - 17/01/2014 - Se quito la opcion para APOSADAS.
LMERIDA - 26/10/2014 - Se cambiaron las tablas cacarrerastb y CAMAINCARRSTB 
          por las vistas CACARRERASVW y CACARRERASPRINCIPALESVW
KHERRERA - 03/02/2015 - Se corrige la opcion de inscritos en historico
*/
PROCEDURE REP_INSCRITOS(
    PUSUARIO  IN DBAFISICC.GNUSUARIOSTB.USUARIO%TYPE,
    PENTIDAD  IN DBAFISICC.GNENTIDADESTB.ENTIDAD%TYPE DEFAULT NULL,
    PDIRECTOR IN DBAFISICC.CACARRERASTB.ENCARGADO%TYPE  DEFAULT NULL,
    PGRADO    IN DBAFISICC.CAGRADOSTB.GRADO%TYPE  DEFAULT NULL,
    PMAINCAR  IN DBAFISICC.CACARRERASTB.MAINCAR%TYPE  DEFAULT NULL,
    PSEDE     IN DBAFISICC.CACARRERASVW.CENTRO%TYPE DEFAULT NULL,
    PANIO     IN NUMBER DEFAULT NULL,
    RETVAL    OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN RETVAL FOR
       SELECT DISTINCT A.CARNET, DECODE(B.SEXO, 'M',A.CARNET,NULL) MASCULINOS,
              DECODE(B.SEXO, 'F',A.CARNET,NULL) FEMENINOS, A.CARRERA, 
			  D.MAINCAR CARRERA_PRINCIPAL,
              D.NOMBRE AS NOMBRE_CARRERA_PRINCIPAL,
              DBAFISICC.PKG_CARRERA.NOMBRE(A.CARRERA, NULL, 1) NOMBRE_CARRERA,
              C.STATUC STATUS, C.CENTRONOMBRE SEDE, TO_NUMBER(A.PERIODO) ANIO,
              F.ENTIDAD||' - '||F.NOMBRE_CORTO||' - '||F.NOMBRE FACULTAD,
              G.GRADO||' - '|| G.DESCRIPCION GRADO,
    --AALVARADO - 09/01/2014 - SE AGREGO STATUS DEL ALUMNO.
              DECODE(A.STATALUM,'IP','PRIMER INGRESO','REINGRESO') STATALUM
            FROM DBAFISICC.CAINSCRITOSTB A, DBAFISICC.CAALUMNOSTB B,
              DBAFISICC.CACARRERASVW C, DBAFISICC.CACARRERASPRINCIPALESVW D,
              DBAFISICC.CAUSUARIOSCARRERASTB E, DBAFISICC.GNENTIDADESTB F,
              DBAFISICC.CAGRADOSTB G
            WHERE A.INSCRITO = 1
              AND C.ENTIDAD    = F.ENTIDAD
              AND F.FACULTAD   = '002'
              AND C.GRADO      = G.GRADO
              AND C.CARRERA    = NVL(A.CARRERA_SEDE, A.CARRERA)
              AND D.CARRERA(+) = C.MAINCAR
              AND C.CARRERA    = E.CARRERA
              AND A.CARNET     = B.CARNET
              AND C.STATUC     = 'A'
              AND E.USUARIO    = PUSUARIO
              AND (PENTIDAD    IS NULL OR C.ENTIDAD     = PENTIDAD)
              AND (PDIRECTOR   IS NULL OR C.ENCARGADO   = PDIRECTOR)
              AND (PGRADO      IS NULL OR C.GRADO       = PGRADO)
              AND (PMAINCAR    IS NULL OR C.CARRERA     = PMAINCAR)
              AND (PSEDE       IS NULL OR C.CENTRO = PSEDE)
          UNION
          SELECT DISTINCT A.CARNET, DECODE(B.SEXO, 'M',A.CARNET,NULL) MASC,
              DECODE(B.SEXO, 'F',A.CARNET,NULL) FEM, A.CARRERA, 
			  D.MAINCAR CARRERA_PRINCIPAL,
            D.NOMBRE AS NOMBRE_CARRERA_PRINCIPAL,
            DBAFISICC.PKG_CARRERA.NOMBRE(A.CARRERA, NULL, 1) NOMBRE_CARRERA,
            C.STATUC STATUS, C.CENTRONOMBRE SEDE,
            EXTRACT(YEAR FROM A.FECHAINSCRITO) AS ANIO,
            F.ENTIDAD||' - '||F.NOMBRE_CORTO||' - '||F.NOMBRE FACULTAD,
            G.GRADO||' - '|| G.DESCRIPCION GRADO,
    --AALVARADO - 09/01/2014 - SE AGREGO STATALUM.      
              DECODE(A.STATALUM,'IP','PRIMER INGRESO','REINGRESO') STATALUM
          FROM DBAFISICC.CAHINSCRITOSTB A, DBAFISICC.CAALUMNOSTB B,
            DBAFISICC.CACARRERASVW C, DBAFISICC.CACARRERASPRINCIPALESVW D,
            DBAFISICC.CAUSUARIOSCARRERASTB E, DBAFISICC.GNENTIDADESTB F,
            DBAFISICC.CAGRADOSTB G
          WHERE A.INSCRITO      = 1
            AND C.ENTIDAD    = F.ENTIDAD
            AND F.FACULTAD   = '002'
            AND C.GRADO      = G.GRADO
            AND A.CARNET        = B.CARNET
            AND C.CARRERA       = NVL(A.CARRERA_SEDE, A.CARRERA)
            AND D.CARRERA(+)    = C.MAINCAR
            AND E.CARRERA       = A.CARRERA
            AND E.USUARIO       = PUSUARIO
            AND (EXTRACT(YEAR FROM A.FECHAINSCRITO) >= PANIO OR PANIO IS NULL)
            AND (PENTIDAD       IS NULL OR C.ENTIDAD     = PENTIDAD)
            AND (PDIRECTOR      IS NULL OR C.ENCARGADO   = PDIRECTOR)
            AND (PGRADO         IS NULL OR C.GRADO       = PGRADO)
            AND (PMAINCAR       IS NULL OR C.CARRERA     = PMAINCAR)
            AND (PSEDE          IS NULL OR C.CENTRO = PSEDE)
          ORDER BY ANIO;
END REP_INSCRITOS;