 /*
autor: Kevin Herrera
FECHA: 05/04/2014
Descripcion: Procedimiento de consultas de la tabla CAREQUISADMXCARRTB.
*/

PROCEDURE REQXCARRERA  
 (
   PCARRERA DBAFISICC.CAREQUISADMXCARRTB.CARRERA%TYPE DEFAULT NULL,
   POPCION varchar2,
   RETVAL  OUT SYS_REFCURSOR
 ) 
 AS BEGIN
 
  IF POPCION = '0' THEN
   OPEN RETVAL FOR
  
    SELECT A.CODREQUIADM, B.NOMBRE 
        FROM DBAFISICC.CAREQUISADMXCARRTB A, DBAFISICC.CAREQUISADMTB B 
        WHERE A.CODREQUIADM= B.CODREQUIADM 
        AND A.CARRERA=PCARRERA;
        
  ELSIF  POPCION = '1' THEN 
   OPEN RETVAL FOR
   
    SELECT CODREQUIADM CODIGO, NOMBRE, CODREQUIADM|| ' - ' ||NOMBRE as NOMBRE2 
      FROM DBAFISICC.CAREQUISADMTB 
      WHERE CODREQUIADM NOT IN (SELECT CODREQUIADM 
                                    FROM DBAFISICC.CAREQUISADMXCARRTB 
                                    WHERE CARRERA=PCARRERA) 
    ORDER BY NOMBRE;  
  END IF;
END REQXCARRERA;  