/*
   Autor: Andrea Alvarado
   Fecha: 26/06/2013
   Descripcion: Revierte la nomina aprobada. 
   
   Modificacion:AALVARADO - 11/07/2013 - Quite que cambie el status al revertir. 
   AALVARADO - 10/08/2013 - agregue el campo PSQLCODE
   
   Modificacion:KHERRERA - 03/10/2014 - Se realiza update en el campo solicitud
                de la tabla RHHDOCENTESTB.
   
*/
 PROCEDURE   REVERTIRNOMINA
( 
   PSOLICITUD    IN DBAFISICC.SOSOLTRAMITETB.SOLICITUD%TYPE,
   PCOMENTARIO   IN DBAFISICC.SOSOLTRAMITETB.COMENTARIOS%TYPE,
   PUSUARIO      IN DBAFISICC.SOSOLTRAMITETB.USUARIO%TYPE,
   PSQLCODE     OUT NUMBER
   
) 
   IS BEGIN 
   
    UPDATE DBAFISICC.RHDOCENTESTB
    SET STATUS = DECODE(STATUS, 'I','B','P'),
        SOLICITUD = NULL
    WHERE SOLICITUD = PSOLICITUD; 
    
    UPDATE DBAFISICC.RHHDOCENTESTB
    SET  SOLICITUD = NULL
    WHERE SOLICITUD = PSOLICITUD; 
    
    DELETE FROM DBAFISICC.NODOCXHORARIOTB
    WHERE RESOLUCION = PSOLICITUD;    
      
    DELETE FROM DBAFISICC.NOHDOCXHORARIOTB
    WHERE RESOLUCION = PSOLICITUD; 
   
    STANDARD.COMMIT;  
    PSQLCODE:=SQLCODE; 
     EXCEPTION 
       WHEN OTHERS THEN 
         PSQLCODE:= SQLCODE;
        
 END REVERTIRNOMINA;