 /*
autor: Kevin Herrera
FECHA: 28/08/2014
Descripcion: Procedimiento que devuelve los salones reservados.               
*/

 PROCEDURE SALONESENUSO  
 (
   PTORRE  IN DBAFISICC.CAHORARIOSTB.TORRE%TYPE,
   PNIVEL  IN DBAFISICC.CAHORARIOSTB.SALON%TYPE,
   PFECHA  IN DBAFISICC.CAMAINHORARIOSTB.FECHAINI%TYPE,
   PDIA    IN DBAFISICC.CAHORARIOSTB.DIA%TYPE,
   RETVAL  OUT SYS_REFCURSOR
 ) 
 AS BEGIN    
  open RETVAL for 

    SELECT DISTINCT(A.SALON), A.HORARIO AS HORARIO,
    TO_CHAR(A.HORAINI,'HH24:MI')AS HORAINI,
    TO_CHAR(A.HORAFIN,'HH24:MI')AS HORAFIN
       
       FROM DBAFISICC.CAHORARIOSTB A,DBAFISICC.CAMAINHORARIOSTB B 
       WHERE A.TORRE=PTORRE 
       AND A.SALON LIKE PNIVEL || '%'
       AND TRUNC(PFECHA) BETWEEN TRUNC(B.FECHAINI) AND TRUNC(B.FECHAFIN) 
       AND A.DIA = PDIA
       AND B.HORARIO = A.HORARIO;
 
 END SALONESENUSO;