  SELECT DISTINCT(A.SALON) AS SSALON, A.HORARIO AS HORARIO,TO_CHAR(A.HORAINI,'DD-MM-YY HH24:MI')AS HORAINI,TO_CHAR(A.HORAFIN,'DD-MM-YY HH24:MI')AS HORAFIN
  FROM CAHORARIOSTB A,CAMAINHORARIOSTB B 
  WHERE A.TORRE=:PTORRE AND A.SALON LIKE :PNIVEL || '%'
  AND trunc(:PFECHA) BETWEEN trunc(B.FECHAINI) AND trunc(B.FECHAFIN) 
  AND A.DIA = :PDIA
  and b.horario = a.horario;