  /*
autor: Kevin Herrera
FECHA: 28/08/2014
Descripcion: Procedimiento para Insertar los nuevos eventos en las tablas 
             correspondientes.
*/

PROCEDURE SOLICITARSALONEVENTO 
 (  
   PDESCRIPCION  IN DBAFISICC.CAMAINHORARIOSTMP.DESCRIPCION%TYPE,  
   PFECHAINICIO  IN DBAFISICC.CAMAINHORARIOSTMP.FECHAINI%TYPE, 
   PFECHAFIN     IN DBAFISICC.CAMAINHORARIOSTMP.FECHAFIN%TYPE,
   PSTATUS       IN DBAFISICC.CAMAINHORARIOSTMP.STATUS%TYPE,
   PHORARIO      IN DBAFISICC.CAHORARIOSTMP.HORARIO%TYPE,
   PCORRELATIVO  IN DBAFISICC.CAHORARIOSTMP.CORRELATIVO%TYPE,
   PDIA          IN DBAFISICC.CAHORARIOSTMP.DIA%TYPE,
   PHORAINI      IN DBAFISICC.CAHORARIOSTMP.HORAINI%TYPE,
   PHORAFIN      IN DBAFISICC.CAHORARIOSTMP.HORAFIN%TYPE,
   PTORRE        IN DBAFISICC.CAHORARIOSTMP.TORRE%TYPE,
   PSALON        IN DBAFISICC.CAHORARIOSTMP.SALON%TYPE,
   PCODPERS      IN DBAFISICC.CAHORARIOSTMP.CODPERS%TYPE,
   PCUPO         IN DBAFISICC.CARESERVHORATMP.CUPO%TYPE,
   PSOLICITANTE  IN DBAFISICC.CARESERVHORATMP.SOLICITANTE%TYPE,
   PUSUARIO      IN DBAFISICC.CARESERVHORATMP.USUARIO%TYPE,
   PEMAIL        IN DBAFISICC.CARESERVHORATMP.EMAIL%TYPE,
   PUSO          IN DBAFISICC.CARESERVHORATMP.USO%TYPE,
   PSQLCODE      OUT NUMBER  
 )
  IS  
  BEGIN  
               
      INSERT INTO DBAFISICC.CAMAINHORARIOSTMP(HORARIO, DESCRIPCION, FECHAINI, 
      FECHAFIN, STATUS) 
          
      values(PHORARIO, PDESCRIPCION, PFECHAINICIO, PFECHAFIN, PSTATUS);
                      
                      
      INSERT INTO DBAFISICC.CAHORARIOSTMP(HORARIO, CORRELATIVO, DIA, HORAINI,
      HORAFIN, SALON, TORRE, CODPERS) 
                    
      VALUES(PHORARIO, PCORRELATIVO, PDIA, PHORAINI, PHORAFIN, PSALON, PTORRE, 
      PCODPERS);
                      
      INSERT INTO DBAFISICC.CARESERVHORATMP(CODIGO, FECHASOLIC, DESCRIPCION,
      SOLICITANTE, CUPO, STATUS, INTERNET, USUARIO, EMAIL, USO) 
        
      VALUES(PHORARIO, PFECHAINICIO, PDESCRIPCION, PSOLICITANTE, PCUPO, 
      PSTATUS, 'S', PUSUARIO, PEMAIL, PUSO);
        
      PSQLCODE := SQLCODE;  
      
      EXCEPTION  
        WHEN OTHERS  THEN  
            PSQLCODE := SQLCODE;
        
 END SOLICITARSALONEVENTO;