/*AUTOR: KEVIN HERRERA    
  FECHA: 06/02/2014   
  DESCRIPCION: PROCEDIMIENTO QUE DEVUELVE LOS TIPOS DE TRAMITE DONDE    
  APLICACION = SA  */ 
  
  procedure TIPOTRAMITE_ASISTECNICA  
  (    
    RETVAL  OUT SYS_REFCURSOR  
  )    
  as      
  begin    
  open RETVAL for     
  
  select TRAMITE, DESCRIPCION, TIPO, REGULAR, MINIMO, MAXIMO, APLICACION         
    from
       DBAFISICC.SOTRAMITESTB         
    where APLICACION = 'SA'    
ORDER BY DESCRIPCION;  
end TIPOTRAMITE_ASISTECNICA;