/*  
Nombre:       DBAFISICC.PKG_Catalogo.TR_CACENTROSTB  
Autor:        Luis Alberto  
Fecha:        2012-07-25  
Package:      PKG_Catalogo  
Descripcion:  Mantenimiento para centros  
              Insertar y actualizar  
Modificaciones:   
Miguel Barillas - 18/10/2013 - Se agrego el insert a AUDITORIA_DB.CaCentrosUsrTB
para que no se haga con un query incrustado.

Autor: Kevin Herrera
Fecha: 07/06/2014
Modificacion: Se agregan al procedimiento los campos: IDEA, ALIAS, STATUS, 
              TIPO, FECHACREACION, IDEACORR, ZONA, CICLO, UG, UFM

*/  
PROCEDURE TR_CACENTROSTB  
(  
  PCODIGO      IN DBAFISICC.CACENTROSTB.CODIGO%TYPE,
  PNOMBRE      IN DBAFISICC.CACENTROSTB.NOMBRE%TYPE DEFAULT NULL,
  PDIRECCION   IN DBAFISICC.CACENTROSTB.DIRECCION%TYPE DEFAULT NULL,
  PPAIS        IN DBAFISICC.CACENTROSTB.PAIS%TYPE DEFAULT NULL,
  PDEPTO       IN DBAFISICC.CACENTROSTB.DEPTO%TYPE DEFAULT NULL,
  PMUNI        IN DBAFISICC.CACENTROSTB.MUNI%TYPE DEFAULT NULL,
  PTELEFONO    IN DBAFISICC.CACENTROSTB.TELEFONO%TYPE DEFAULT NULL,
  PENCARGADO   IN DBAFISICC.CACENTROSTB.ENCARGADO%TYPE DEFAULT NULL,
  PEMAIL       IN DBAFISICC.CACENTROSTB.EMAIL%TYPE DEFAULT NULL,
  PFAX         IN DBAFISICC.CACENTROSTB.FAX%TYPE DEFAULT NULL,
  PAGENCIA     IN DBAFISICC.CACENTROSTB.AGENCIA%TYPE DEFAULT NULL,
  PIDEA        IN DBAFISICC.CACENTROSTB.IDEA%TYPE DEFAULT NULL,
  PALIAS       IN DBAFISICC.CACENTROSTB.ALIAS%TYPE DEFAULT NULL,
  PUSUARIO     IN DBAFISICC.GNUSUARIOSTB.USUARIO%TYPE DEFAULT NULL,
  PSTATUS      IN DBAFISICC.CACENTROSTB.STATUS%TYPE DEFAULT NULL,
  PTIPO        IN DBAFISICC.CACENTROSTB.TIPO%TYPE DEFAULT NULL,
  PFECHA       IN DBAFISICC.CACENTROSTB.FECHACREACION%TYPE DEFAULT NULL,
  PCORRELATIVO IN DBAFISICC.CACENTROSTB.IDEACORR%TYPE DEFAULT NULL,
  PZONA        IN DBAFISICC.CACENTROSTB.ZONA%TYPE DEFAULT NULL,
  PCICLO       IN DBAFISICC.CACENTROSTB.CICLO%TYPE DEFAULT NULL,
  PUG          IN DBAFISICC.CACENTROSTB.UG%TYPE DEFAULT NULL,
  PUFM         IN DBAFISICC.CACENTROSTB.UFM%TYPE DEFAULT NULL,
  PACCION      IN VARCHAR2,
  PSQLCODE     OUT NUMBER  
) IS  
  BEGIN  
      
  IF PACCION = 'I' THEN  
      
    INSERT INTO DBAFISICC.CACENTROSTB A(A.CODIGO, A.NOMBRE, A.DIRECCION, A.PAIS, 
    A.DEPTO, A.MUNI, A.TELEFONO, A.ENCARGADO, A.EMAIL, A.FAX, A.AGENCIA, 
    A.IDEA, A.ALIAS, A.STATUS, A.TIPO, A.FECHACREACION, A.IDEACORR, A.ZONA, 
    A.CICLO, A.UG, A.UFM)  
    
    VALUES(PCODIGO, PNOMBRE, PDIRECCION, PPAIS, PDEPTO, PMUNI, PTELEFONO,
    PENCARGADO, PEMAIL, PFAX, PAGENCIA, PIDEA, PALIAS, PSTATUS, PTIPO, PFECHA,
    PCORRELATIVO, PZONA, PCICLO, PUG, PUFM);  
      
  ELSIF PACCION = 'U' THEN  
      
    UPDATE DBAFISICC.CACENTROSTB A
      SET  A.NOMBRE = PNOMBRE, A.DIRECCION = PDIRECCION, A.PAIS = PPAIS,
      A.DEPTO = PDEPTO, A.MUNI = PMUNI, A.TELEFONO = PTELEFONO, 
      A.ENCARGADO = PENCARGADO, A.EMAIL = PEMAIL, A.FAX = PFAX, 
      A.AGENCIA = PAGENCIA, A.IDEA = PIDEA, A.ALIAS = PALIAS, 
      A.STATUS = PSTATUS, A.TIPO = PTIPO, A.FECHACREACION = PFECHA, 
      A.IDEACORR = PCORRELATIVO, A.ZONA = PZONA, A.CICLO = PCICLO, A.UG = PUG,
      A.UFM = PUFM
         WHERE A.CODIGO = PCODIGO;
         
   ELSIF PACCION = 'D' THEN  
      
    DELETE DBAFISICC.CACENTROSTB 
         WHERE CODIGO = PCODIGO;       
 
  END IF;

	INSERT INTO AUDITORIA_DB.CACENTROSUSRTB B(B.CODIGO, B.NOMBRE, B.DIRECCION,
  B.PAIS, B.DEPTO, B.MUNI, B.TELEFONO, B.ENCARGADO, B.EMAIL, B.FAX, B.AGENCIA,
  B.MOVIMIENTO, B.USUARIO, B.FECHA, B.STATUS, B.TIPO, B.FECHACREACION, 
  B.IDEACORR, B.ZONA, B.CICLO, B.UG, B.UFM)
	  
  SELECT CODIGO, NOMBRE, DIRECCION, PAIS, DEPTO, MUNI, TELEFONO, ENCARGADO,
  EMAIL, FAX, AGENCIA, PACCION, PUSUARIO, SYSDATE, STATUS, TIPO, FECHACREACION,
  IDEACORR, ZONA, CICLO, UG, UFM
		
      FROM DBAFISICC.CACENTROSTB 
	  	WHERE CODIGO = PCODIGO;

      PSQLCODE := SQLCODE;

  EXCEPTION  
  WHEN OTHERS
	THEN

      PSQLCODE := SQLCODE;

END TR_CACENTROSTB; 