 /*
autor: Kevin Herrera
FECHA: 28/04/2014
Descripcion: Procedimiento para Insertar, actualizar y editar los datos de 
             la tabla GNPROFESIONESTB.
*/

PROCEDURE TR_CACICLOSVIGENTESTMP  
 (  
    PUSUARIO   IN AUDITORIA_DB.CACICLOSVIGENTESUSRTMP.USUARIO%TYPE DEFAULT NULL,  
    PCARRERA   IN DBAFISICC.CACICLOSVIGENTESTMP.CARRERA%TYPE DEFAULT NULL,  
    PPENSUM    IN DBAFISICC.CACICLOSVIGENTESTMP.PENSUM%TYPE DEFAULT NULL,  
    PCICLO     IN DBAFISICC.CACICLOSVIGENTESTMP.CICLO%TYPE DEFAULT NULL, 
    PCICLO2    IN DBAFISICC.CACICLOSVIGENTESTMP.CICLO%TYPE DEFAULT NULL, 
    PACCION    VARCHAR2,
    PSQLCODE   OUT NUMBER
 )
 
  IS  
  BEGIN  
    
  IF PACCION = 'I'  THEN
  
    INSERT INTO DBAFISICC.CACICLOSVIGENTESTMP (CARRERA, PENSUM, CICLO)
    VALUES (PCARRERA, PPENSUM, PCICLO);
  
  ELSIF PACCION = 'U'  THEN            

    UPDATE DBAFISICC.CACICLOSVIGENTESTMP
    SET CICLO = PCICLO2
    WHERE CARRERA = PCARRERA
    AND PENSUM = PPENSUM
    AND PCICLO = PCICLO;
  
  ELSIF PACCION = 'D'  THEN                   
    
    DELETE FROM DBAFISICC.CACICLOSVIGENTESTMP
    WHERE CARRERA = PCARRERA
    AND PENSUM = PPENSUM
    AND PCICLO = PCICLO;
  
  END IF;  
  
  
  INSERT INTO AUDITORIA_DB.CACICLOSVIGENTESUSRTMP(CARRERA, PENSUM, CICLO, 
  PMOVIMIENTO, USUARIO, FECHA)
  
  SELECT CARRERA, PENSUM, CICLO, PACCION, PUSUARIO, SYSDATE
    FROM DBAFISICC.CACICLOSVIGENTESTMP
    WHERE CARRERA = PCARRERA
    AND PENSUM = PPENSUM
    AND CICLO = PCICLO;
                   
      PSQLCODE := SQLCODE;
      
      EXCEPTION  
      WHEN OTHERS  THEN  
        PSQLCODE := SQLCODE;

END TR_CACICLOSVIGENTESTMP;   