 /*
autor: Kevin Herrera
FECHA: 22/03/2014
Descripcion: Procedimiento que devuelve la informacion de las carreras
             y tambien actualiza esta informacion.
*/
PROCEDURE TR_CACARRERASTB
(
    PCARRERA DBAFISICC.CACARRERASTB.CARRERA%TYPE DEFAULT NULL,
    PENTIDAD DBAFISICC.CACARRERASTB.ENTIDAD%TYPE DEFAULT NULL,
    PSTATUC DBAFISICC.CACARRERASTB.STATUC%TYPE DEFAULT NULL,
    PPERIODO DBAFISICC.CACARRERASTB.PERIODO%TYPE DEFAULT NULL,
    PNEXTTERM DBAFISICC.CACARRERASTB.NEXTTERM%TYPE DEFAULT NULL,
    PNOMBRE DBAFISICC.CACARRERASTB.NOMBRE%TYPE DEFAULT NULL,
    PTIPOCICLO DBAFISICC.CACARRERASTB.TIPOCICLO%TYPE DEFAULT NULL,
    PCOBROINS DBAFISICC.cacarrerastb.cobroins%TYPE DEFAULT NULL,
    PPRECIO DBAFISICC.CACARRERASTB.PRECIO%TYPE DEFAULT NULL,
    PTIPOCOBRO DBAFISICC.CACARRERASTB.TIPOCOBRO%TYPE DEFAULT NULL,
    PMUXCT DBAFISICC.CACARRERASTB.MUXCT%TYPE DEFAULT NULL,
    PLIQUIDACION DBAFISICC.CACARRERASTB.LIQUIDACION%TYPE DEFAULT NULL,
    PPAGODOCENTES DBAFISICC.CACARRERASTB.PAGODOCENTES%TYPE DEFAULT NULL,
    PTIPO DBAFISICC.CACARRERASTB.TIPO%TYPE DEFAULT NULL,
    PLOCALIDAD DBAFISICC.CACARRERASTB.LOCALIDAD%TYPE DEFAULT NULL,
    PPENSUM_VIGENTE DBAFISICC.CACARRERASTB.PENSUM_VIGENTE%TYPE DEFAULT NULL,
    PCOMENTARIOS DBAFISICC.CACARRERASTB.COMENTARIOS%TYPE DEFAULT NULL,
    PNOMBRE_CORTO DBAFISICC.CACARRERASTB.NOMBRE_CORTO%TYPE DEFAULT NULL,
    PCC DBAFISICC.CACARRERASTB.CC%TYPE DEFAULT NULL,
    PGRADO DBAFISICC.CACARRERASTB.GRADO%TYPE DEFAULT NULL,
    PAGENCIA DBAFISICC.CACARRERASTB.AGENCIA%TYPE DEFAULT NULL,
    PUBICACION DBAFISICC.CACARRERASTB.UBICACION%TYPE DEFAULT NULL,
    PNOMBRE_INGLES DBAFISICC.CACARRERASTB.NOMBRE_INGLES%TYPE DEFAULT NULL,
    PPBMT DBAFISICC.CACARRERASTB.PBMT%TYPE DEFAULT NULL,
    PPBCT DBAFISICC.CACARRERASTB.PBCT%TYPE DEFAULT NULL,
    PPERIODOCLASE DBAFISICC.CACARRERASTB.PERIODOCLASE%TYPE DEFAULT NULL,
    PORDEN DBAFISICC.CACARRERASTB.ORDEN%TYPE DEFAULT NULL,
    PPRIVADO DBAFISICC.CACARRERASTB.PRIVADO%TYPE DEFAULT NULL,
    PPERIODOSXSEMANA DBAFISICC.CACARRERASTB.PERIODOSXSEMANA%TYPE DEFAULT NULL,
    PSIGNATURE DBAFISICC.CACARRERASTB.SIGNATURE%TYPE DEFAULT NULL,
    PACCION varchar2
)
 IS
 BEGIN
 
   if PACCION = 'U' THEN
     
      UPDATE dbafisicc.cacarrerastb
      SET  ENTIDAD = PENTIDAD, STATUC = PSTATUC, PERIODO = PPERIODO, 
           NEXTTERM = PNEXTTERM, NOMBRE = PNOMBRE, TIPOCICLO = PTIPOCICLO, 
           COBROINS = PCOBROINS, PRECIO = PPRECIO, TIPOCOBRO = PTIPOCOBRO, 
           MUXCT = PMUXCT, LIQUIDACION = PLIQUIDACION, 
           PAGODOCENTES = PPAGODOCENTES, TIPO = PTIPO, LOCALIDAD = PLOCALIDAD, 
           PENSUM_VIGENTE = PPENSUM_VIGENTE, COMENTARIOS = PCOMENTARIOS, 
           NOMBRE_CORTO = PNOMBRE_CORTO, CC = PCC, GRADO = PGRADO, 
           AGENCIA = PAGENCIA, UBICACION = PUBICACION,
           NOMBRE_INGLES = PNOMBRE_INGLES, PBMT = PPBMT, PBCT = PPBCT, 
           PERIODOCLASE = PPERIODOCLASE, ORDEN = PORDEN, PRIVADO = PPRIVADO, 
           PERIODOSXSEMANA = PPERIODOSXSEMANA, SIGNATURE = PSIGNATURE
       
        WHERE carrera = PCARRERA;
        
      END IF;
END TR_CACARRERASTB;