 /*
autor: Kevin Herrera
FECHA: 05/04/2014
Descripcion: Procedimiento que inserta y elimina datos de la tabla
             CAREQUISADMXCARRTB.
*/

PROCEDURE TR_CAREQUISADMXCARRTB  
(
  PCARRERA DBAFISICC.CAREQUISADMXCARRTB.CARRERA%TYPE DEFAULT NULL,
  PCODIGO DBAFISICC.CAREQUISADMXCARRTB.CODREQUIADM%TYPE DEFAULT NULL,
  PACCION varchar2
) 
 AS BEGIN 
 
 IF PACCION = 'I' THEN
 
     INSERT INTO DBAFISICC.CAREQUISADMXCARRTB (CODREQUIADM, CARRERA) 
     VALUES(PCODIGO,PCARRERA); 

 ELSIF PACCION = 'D' THEN
    
     DELETE FROM DBAFISICC.CAREQUISADMXCARRTB
            WHERE CODREQUIADM = PCODIGO
            AND   CARRERA = PCARRERA;
  END IF;

END TR_CAREQUISADMXCARRTB;  