 /*
autor: Kevin Herrera
FECHA: 28/04/2014
Descripcion: Procedimiento para Insertar, actualizar y editar los datos de 
             la tabla GNPROFESIONESTB.
*/

CREATE OR REPLACE PROCEDURE TR_GNPROFESIONESTB  
 (  
   PCODIGO       IN DBAFISICC.GNPROFESIONESTB.CODPROF%TYPE,  
   PDESCRIPCION  IN DBAFISICC.GNPROFESIONESTB.DESCRIPCION%TYPE,  
   PACCION       IN VARCHAR2,
   PSQLCODE OUT NUMBER  
 )
  IS  
  BEGIN  
    
  IF PACCION = 'I'  THEN
  
    INSERT INTO DBAFISICC.GNPROFESIONESTB(CODPROF, DESCRIPCION)
    values(PCODIGO, PDESCRIPCION);
  
  ELSIF PACCION = 'U'  THEN            

    UPDATE DBAFISICC.gnprofesionestb
     SET DESCRIPCION = PDESCRIPCION
     WHERE CODPROF=PCODIGO;
  
  ELSIF PACCION = 'D'  THEN                   
    
    DELETE FROM DBAFISICC.GNPROFESIONESTB
           WHERE CODPROF=PCODIGO;
  
  END IF;  
            
  PSQLCODE := SQLCODE;  
      
  EXCEPTION  
    WHEN OTHERS  THEN  
        PSQLCODE := SQLCODE;

END TR_GNPROFESIONESTB;   