 /*
autor: Kevin Herrera
FECHA: 24/04/2014
Descripcion: Procedimiento para Insertar, actualizar y editar los datos de 
             la tabla GNHOSPITALESTB.
*/

PROCEDURE TR_GNHOSPITALESTB  
 (  
   PHOSPITAL      IN DBAFISICC.GNHOSPITALESTB.HOSPITAL%TYPE,  
   PDESCRIPCION   IN DBAFISICC.GNHOSPITALESTB.DESCRIPCION%TYPE,  
   PACCION        IN VARCHAR2,
   PSQLCODE OUT NUMBER  
 )
  IS  
  BEGIN  
    
  IF PACCION = 'I'  THEN
  
    INSERT INTO DBAFISICC.GNHOSPITALESTB(HOSPITAL,DESCRIPCION)
    VALUES(PHOSPITAL, PDESCRIPCION);
       
  
  ELSIF PACCION = 'U'  THEN            
    
    UPDATE DBAFISICC.GNHOSPITALESTB
     SET DESCRIPCION = PDESCRIPCION
     WHERE HOSPITAL=PHOSPITAL;
  
  ELSIF PACCION = 'D'  THEN                   
    
    DELETE FROM DBAFISICC.GNHOSPITALESTB
           WHERE HOSPITAL=PHOSPITAL;
  
  END IF;  
            
  PSQLCODE := SQLCODE;  
      
  EXCEPTION  
    WHEN OTHERS  THEN  
        PSQLCODE := SQLCODE;

END TR_GNHOSPITALESTB;        