/*
Autor:  Kevin Herrera.
Fecha:  21/07/2014
Descripcion: Procedimiento que permite insertar o actualizar los datos de 
             asistencia de los Docentes en la tabla RHASISTENCIATB.
*/

PROCEDURE TR_RHASISTENCIATB
 (
    PHORARIO      DBAFISICC.RHASISTENCIATB.HORARIO%TYPE DEFAULT NULL,
    PCORRELATIVO  DBAFISICC.RHASISTENCIATB.CORRELATIVO%TYPE DEFAULT NULL,
    PFECHA        DBAFISICC.RHASISTENCIATB.FECHA%TYPE DEFAULT NULL,
    PAUSENCIA     DBAFISICC.RHASISTENCIATB.AUSENCIA%TYPE DEFAULT NULL,
    PPUNTUALIDAD  DBAFISICC.RHASISTENCIATB.PUNTUALIDAD%TYPE DEFAULT NULL,
    PTIEMPO       DBAFISICC.RHASISTENCIATB.TIEMPO%TYPE DEFAULT NULL,
    PCOMENTARIOS  DBAFISICC.RHASISTENCIATB.COMENTARIOS%TYPE DEFAULT NULL,
    PAVISO        DBAFISICC.RHASISTENCIATB.AVISO%TYPE DEFAULT NULL,
    PALUMNOS      DBAFISICC.RHASISTENCIATB.ALUMNOS%TYPE DEFAULT NULL,
    PASIGNADOS    DBAFISICC.RHASISTENCIATB.ASIGNADOS%TYPE DEFAULT NULL,
    PATENDIO      DBAFISICC.RHASISTENCIATB.ATENDIO%TYPE DEFAULT NULL,
    PCODPERS      DBAFISICC.RHASISTENCIATB.CODPERS%TYPE DEFAULT NULL,
    PPUESTO       DBAFISICC.RHASISTENCIATB.CODPUESTO%TYPE DEFAULT NULL,
    PUSUARIO      DBAFISICC.AUDRHASISTENCIAUSRTB.USUARIO%TYPE DEFAULT NULL,
    PACCION       VARCHAR2,
    PSQLCODE      OUT NUMBER
 )
  IS BEGIN
  
  IF PACCION = 'I' THEN
  
      INSERT INTO DBAFISICC.RHASISTENCIATB (HORARIO, CORRELATIVO, FECHA, 
      AUSENCIA, PUNTUALIDAD, TIEMPO, COMENTARIOS, AVISO, ALUMNOS, ASIGNADOS, 
      ATENDIO, CODPERS, CODPUESTO)
      
      VALUES(PHORARIO, PCORRELATIVO, PFECHA, PAUSENCIA, PPUNTUALIDAD, PTIEMPO,
      PCOMENTARIOS, PAVISO, PALUMNOS, PASIGNADOS, PATENDIO, PCODPERS, PPUESTO);
      
  ELSIF PACCION = 'U' THEN    
  
      UPDATE DBAFISICC.RHASISTENCIATB
      SET AUSENCIA = PAUSENCIA, PUNTUALIDAD = PPUNTUALIDAD, TIEMPO=PTIEMPO, 
      COMENTARIOS=PCOMENTARIOS, AVISO=PAVISO, ALUMNOS=PALUMNOS, 
      ASIGNADOS=PASIGNADOS, ATENDIO=PATENDIO
      WHERE HORARIO=PHORARIO
      AND CORRELATIVO=PCORRELATIVO
      AND TRUNC(FECHA)=TRUNC(PFECHA) 
      AND CODPUESTO=PPUESTO
      AND CODPERS=PCODPERS;
  
  END IF;
      
      INSERT INTO DBAFISICC.AUDRHASISTENCIAUSRTB (HORARIO, CORRELATIVO, FECHA, 
      AUSENCIA, PUNTUALIDAD, TIEMPO, COMENTARIOS, AVISO, ALUMNOS, ASIGNADOS, 
      ATENDIO, CODPERS, CODPUESTO, USUARIO, FECHATRANSACCION, MOVIMIENTO) 
      
      VALUES(PHORARIO, PCORRELATIVO, PFECHA, PAUSENCIA, PPUNTUALIDAD, PTIEMPO,
      PCOMENTARIOS, PAVISO, PALUMNOS, PASIGNADOS, PATENDIO, PCODPERS, PPUESTO,
      PUSUARIO, SYSDATE, PACCION);
  
  PSQLCODE := SQLCODE;  
      
  EXCEPTION  
    WHEN OTHERS  THEN  
        PSQLCODE := SQLCODE;
        
END TR_RHASISTENCIATB;