/*
Autor:  Kevin Herrera.
Fecha:  21/07/2014
Descripcion: Procedimiento que permite insertar o actualizar los datos de 
             asistencia de los alumnos en la tabla RHALUMASISTETB.
*/

PROCEDURE TR_RHALUMASISTETB
 (
    PHORARIO      DBAFISICC.RHALUMASISTETB.HORARIO%TYPE DEFAULT NULL,
    PCORRELATIVO  DBAFISICC.RHALUMASISTETB.CORRELATIVO%TYPE DEFAULT NULL,
    PFECHA        DBAFISICC.RHALUMASISTETB.FECHA%TYPE DEFAULT NULL,
    PCARNET       DBAFISICC.RHALUMASISTETB.CARNET%TYPE DEFAULT NULL,
    PCARRERA      DBAFISICC.RHALUMASISTETB.CARRERA%TYPE DEFAULT NULL,
    PAUSENCIA     DBAFISICC.RHALUMASISTETB.AUSENCIA%TYPE DEFAULT NULL,
    PUSUARIO      DBAFISICC.AUDRHALUMASISTEUSRTB.USUARIO%TYPE DEFAULT NULL,
    PACCION       VARCHAR2,
    PSQLCODE      OUT NUMBER
 )
  IS BEGIN
  
  IF PACCION = 'I' THEN
  
          INSERT INTO DBAFISICC.RHALUMASISTETB (HORARIO, CORRELATIVO, FECHA, 
          CARNET, CARRERA, AUSENCIA)
            
          VALUES (PHORARIO, PCORRELATIVO, PFECHA, PCARNET, PCARRERA, PAUSENCIA);
   
  ELSIF PACCION = 'U' THEN  
      
          UPDATE DBAFISICC.RHALUMASISTETB 
          SET AUSENCIA = PAUSENCIA
          WHERE HORARIO = PHORARIO 
          AND CORRELATIVO = PCORRELATIVO 
          AND TRUNC(FECHA) = TRUNC(PFECHA)
          AND CARNET = PCARNET
          AND CARRERA = PCARRERA;
          
  END IF;         
          
          INSERT INTO DBAFISICC.AUDRHALUMASISTEUSRTB (HORARIO, CORRELATIVO, 
          FECHA, CARNET, CARRERA, AUSENCIA, USUARIO, FECHATRANSACCION, 
          MOVIMIENTO)
          
          VALUES(PHORARIO, PCORRELATIVO, PFECHA, PCARNET, PCARRERA, PAUSENCIA, 
          PUSUARIO, SYSDATE, PACCION);
  
  PSQLCODE := SQLCODE;  
      
  EXCEPTION  
    WHEN OTHERS  THEN  
        PSQLCODE := SQLCODE;        
   
 END TR_RHALUMASISTETB;    