  /*
autor: Kevin Herrera
FECHA: 28/08/2014
Descripcion: Procedimiento para Insertar en SOINFOTRAMITETB.
*/

PROCEDURE TR_SOINFOTRAMITETB 
 (  
   PCODINFO      IN DBAFISICC.SOINFOTRAMITETB.CODINFO%TYPE,  
   PTRAMITE      IN DBAFISICC.SOINFOTRAMITETB.TRAMITE%TYPE, 
   PNOMCAMPO     IN DBAFISICC.SOINFOTRAMITETB.NOMCAMPO%TYPE, 
   PDESCRIPCION  IN DBAFISICC.SOINFOTRAMITETB.DESCRIPCION%TYPE, 
   PSQLCODE    OUT NUMBER  
 )
  IS  
  BEGIN 
       
       INSERT INTO SOINFOTRAMITETB(CODINFO, TRAMITE, NOMCAMPO, DESCRIPCION)
       VALUES(PCODINFO, PTRAMITE, PNOMCAMPO, PDESCRIPCION);
       
       PSQLCODE := SQLCODE;  
            
            EXCEPTION  
              WHEN OTHERS  THEN  
                  PSQLCODE := SQLCODE;
        
 END TR_SOINFOTRAMITETB;