  /*
autor: Kevin Herrera
FECHA: 28/08/2014
Descripcion: Procedimiento para Insertar en la tabla TR_SOSOLINFOTRAMITETB.
*/

PROCEDURE TR_SOSOLINFOTRAMITETB 
 (  
   PSOLICITUD  IN DBAFISICC.SOSOLINFOTRAMITETB.SOLICITUD%TYPE,  
   PCODINFO    IN DBAFISICC.SOSOLINFOTRAMITETB.CODINFO%TYPE, 
   PTRAMITE    IN DBAFISICC.SOSOLINFOTRAMITETB.TRAMITE%TYPE, 
   PCAMPON     IN DBAFISICC.SOSOLINFOTRAMITETB.CAMPON%TYPE, 
   PCAMPOC     IN DBAFISICC.SOSOLINFOTRAMITETB.CAMPOC%TYPE, 
   PCAMPOF     IN DBAFISICC.SOSOLINFOTRAMITETB.CAMPOF%TYPE, 
   PSQLCODE    OUT NUMBER  
 )
  IS  
  BEGIN

       INSERT INTO DBAFISICC.SOSOLINFOTRAMITETB(SOLICITUD, CODINFO, TRAMITE, 
       CAMPON, CAMPOC, CAMPOF)
        
       VALUES(PSOLICITUD, PCODINFO, PTRAMITE, PCAMPON, PCAMPOC, PCAMPOF);

       PSQLCODE := SQLCODE;  
            
            EXCEPTION  
              WHEN OTHERS  THEN  
                  PSQLCODE := SQLCODE;
        
 END TR_SOSOLINFOTRAMITETB;