/*
Autor:  Kevin Herrera.
Fecha:  21/07/2014
Descripcion: Procedimiento que permite insertar o actualizar los datos de 
             asistencia de los alumnos en la tabla RHALUMASISTETB.
*/

/*
select * from DGETIQUETATB

UPDATE DGETIQUETATB
SET NOMBRE = 'AULAS'
WHERE ETIQUETA = '27'

INSERT INTO DGAPLICACIONESTB
values('AU', 'AULAS', 'I:\AULAS')

INSERT INTO DGCATEGORIASTB
values('AU', 37, 'AULAS', 'AULAS')

INSERT INTO DGETIQUETATB
values(27, 'CROQUIS')

 CREATE TABLE TEMP_INFOEVENTO(
  USUARIO varchar2(20),
  TORRE VARCHAR2(10),
  NIVEL VARCHAR2(10),
  SALON VARCHAR2(10),
  FECHA DATE,
  INICIO NUMBER,
  FIN NUMBER
 );

 );
*/

PROCEDURE TR_TEMP_INFOEVENTO
 (
    PUSUARIO  DBAFISICC.GNUSUARIOSTB.USUARIO%TYPE DEFAULT NULL,
    PTORRE    DBAFISICC.TEMP_INFOEVENTO.TORRE%TYPE DEFAULT NULL,
    PNIVEL    DBAFISICC.TEMP_INFOEVENTO.NIVEL%TYPE DEFAULT NULL,
    PSALON    DBAFISICC.TEMP_INFOEVENTO.SALON%TYPE DEFAULT NULL,
    PFECHA    DBAFISICC.TEMP_INFOEVENTO.FECHA%TYPE DEFAULT NULL,
    PINICIO   DBAFISICC.TEMP_INFOEVENTO.INICIO%TYPE DEFAULT NULL,
    PFIN      DBAFISICC.TEMP_INFOEVENTO.FIN%TYPE DEFAULT NULL,
    PACCION   VARCHAR2,
    PSQLCODE  OUT NUMBER
 )
  IS BEGIN
  
  IF PACCION = 'I' THEN
  
       INSERT INTO TEMP_INFOEVENTO(USUARIO, TORRE, NIVEL, SALON, FECHA, INICIO,
                                   FIN)
       values(PUSUARIO, PTORRE, PNIVEL, PSALON, PFECHA, PINICIO, PFIN);
   
  ELSIF PACCION = 'D' THEN  
      
       DELETE TEMP_INFOEVENTO
       WHERE USUARIO = PUSUARIO;
          
  END IF;         
          
  PSQLCODE := SQLCODE;  
      
  EXCEPTION  
    WHEN OTHERS  THEN  
        PSQLCODE := SQLCODE;        
   
 END TR_TEMP_INFOEVENTO;       